import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "node",
    include: ["tests/**/*.test.ts"],
    coverage: {
      provider: "v8",
      reporter: ["text", "lcov"],
      // Pure modules plus the notebook input adapters covered by lifecycle tests.
      include: [
        "src/changelog.ts",
        "src/settings-data.ts",
        "src/model/**/*.ts",
        "src/ink/freehand.ts",
        "src/ink/stroke-builder.ts",
        "src/ink/shape-recognizer.ts",
        "src/ink/shape-geometry.ts",
        "src/ink/table-geometry.ts",
        "src/ink/stroke-eraser.ts",
        "src/ink/scribble.ts",
        "src/ink/pen-gestures.ts",
        "src/canvas/backdrop.ts",
        "src/canvas/page-layout.ts",
        "src/canvas/hit-test.ts",
        "src/canvas/spatial-index.ts",
        "src/canvas/zoom.ts",
        "src/canvas/scroll-physics.ts",
        "src/canvas/scroll-thumb.ts",
        "src/canvas/tile-grid.ts",
        "src/canvas/image-geometry.ts",
        "src/canvas/image-crop.ts",
        "src/canvas/image-raster.ts",
        "src/canvas/pdf-raster.ts",
        "src/canvas/pdf-tiles.ts",
        "src/canvas/text-layout.ts",
        "src/canvas/lasso.ts",
        "src/view/selection-bar-model.ts",
        "src/view/view-routing.ts",
        "src/view/load-guard.ts",
        "src/view/text-panel.ts",
        "src/view/id-sequence.ts",
        "src/view/stroke-index.ts",
        "src/view/surface-keys.ts",
        "src/view/notebook-keys.ts",
        "src/view/scroll-thumb-drag.ts",
        "src/view/tool-return.ts",
        "src/view/pointer-hud.ts",
        "src/view/surface-size.ts",
        "src/view/write-hold.ts",
        "src/view/view-rest.ts",
        "src/view/file-moves.ts",
        "src/canvas/scan-raster.ts",
        "src/canvas/homography.ts",
        "src/canvas/page-detect.ts",
        "src/canvas/scan-filters.ts",
        "src/input/palm-rejection.ts",
        "src/input/pen-rejoin.ts",
        "src/input/finger-gesture.ts",
        "src/input/multitouch-double-tap.ts",
        "src/view/multitouch-input.ts",
        "src/recognition/text-layer.ts",
        "src/recognition/registry.ts",
        "src/recognition/manual.ts",
        "src/recognition/llm-request.ts",
        "src/recognition/openrouter-auth.ts",
        "src/recognition/ai-chat.ts",
        "src/recognition/ai-image.ts",
        "src/recognition/ai-menu-model.ts",
        "src/recognition/ai-placement.ts",
        "src/recognition/audio-request.ts",
        "src/recognition/key-store.ts",
        "src/recognition/page-transcripts.ts",
        "src/audio/recording.ts",
        "src/export/pdf-writer.ts",
        "src/export/pdf-composer.ts",
        "src/export/annotation-layers.ts",
        "src/export/page-range.ts",
        "src/search/notebook-search.ts",
        "src/util/errors.ts",
      ],
      thresholds: {
        "src/canvas/zoom.ts": { lines: 100, functions: 100, statements: 100, branches: 100 },
        lines: 80,
        functions: 80,
        statements: 80,
        branches: 70,
        "src/{canvas/scroll-thumb,view/surface-keys,view/notebook-keys,view/scroll-thumb-drag}.ts":
          {
            lines: 100,
            functions: 100,
            statements: 100,
            branches: 100,
          },
        "src/view/tool-return.ts": { lines: 100, functions: 100, statements: 100, branches: 100 },
      },
    },
  },
});
